def foo() -> void:
    x: byte = 'a'
    x += 123 as byte  # no error
    x += 123  # Error: addition produced a value of type int which cannot be assigned back to byte
